config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'transactions#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[create new show]
  resources :groups, only: %i[index create new show]
  resources :transactions, only: %i[index create new show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  belongs_to :user
  has_many :transactions, dependent: :destroy
  validates :icon, presence: true
  # content_type: { in: %w[image/jpeg image/gif image/png],
  # message: "must be a valid image format" },
  # size:
  # { less_than: 5.megabytes,
  # message:
  # "should be less than 5MB" }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :name, :amount, presence: true
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  has_many :created_groups, class_name: 'Group', foreign_key: :user_id
  has_many :created_transactions, class_name: 'Transaction', foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :not_blank?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'you must be logged in to perfom that action'
    redirect_to login_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in?, only: [:create]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.created_groups.build(group_params)
    @group.icon.attach(params[:group][:icon])
    if @group.save
      flash.notice = 'Group created'
      redirect_to @group
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if params[:session][:username].blank?
      render 'new'
      flash.alert = 'Please enter your name'
    else
      user = User.find_by_username(params[:session][:username])
      if user.present?
        session[:user_id] = user.id
        redirect_to root_url, notice: 'Logged in!'
      else
        flash.now[:alert] = 'sign up before you login'
        render 'new'
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :logged_in?, only: [:create]

  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.created_transactions.build(transaction_params)
    if @transaction.save
      flash.notice = 'Transaction created'
      redirect_to @transaction
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @created_transactions = @user.created_transactions
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = "Account created succesfully welcome #{@user.username}.Please sign in."
      redirect_to login_path
    else
      flash.now[:notice] = 'Please enter your name'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class = "container mt-3"> 
   
 <h3>All Groups</h3>
    <%= link_to 'Create new Group', new_group_path, class: 'btn custom mb-2' %>
  <% @groups.order("name asc").each do |group| %>
  <div class = 'row'>
    <div class = 'col-10 card p-3 text-center'>
      
        <p><%= image_tag group.icon, class: "icon" %></p>
        <p><strong>Name:</strong> <%= group.name %></p>
        <p><strong>Created At:</strong> <%= group.created_at %></p>
        <p><%= link_to 'VIEW', group_path(group), class: 'btn custom' %> </p>
    </div>
  </div>
   <% end %>
</div>

app/views/groups/new.html.erb
<div class="row container h-4">
  <div class="col-6 ">
    <div class="container mt-3 card-bg shdw p-3">
  <h1 class="mt-3">Create a Group</h1>
<%= form_with(model: @group, class: "shadow p-3 mb-3 form-bg rounded", local: true) do |f| %>

<div class="form-group ">
  <%=f.label :name%>
  <%=f.text_field :name, class: "form-control"%>
</div>
<div class="form-group ">
  <%=f.label :icon %>
  <%=f.file_field :icon, accept: "image/jpeg,image/gif,image/png", class: "form-control", direct_upload: true %>
</div>
  <div class="form-group">
    <%=f.submit "Create Group", class: "btn btn-success"%>
  </div>
  
<% end %>
</div>
    
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
<h1>Group <%=%></h1>
<%= link_to 'ADD NEW', new_group_path, class: 'btn custom' %>
    <% @group.transactions.each do |t| %>
        <div class = 'row'>
            <div class = 'col-10 card p-3 text-center'>       
                <p><strong>Username:</strong> <%= t.user.username.capitalize %></p>
                <p><strong>Transaction name:</strong> <%= t.name %></p>
                <p><strong>Amount:</strong> $<%= t.amount %></p>
                <p><strong>created at:</strong> <%= t.created_at %></p> 
            </div>
        </div>
    <%end%>

</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer p-3 text-white mt-5">
    <div class="container text-center">
        <small>Copyright &copy; <%=link_to "Rails Capstone", "#", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success text-center w-50 container mt-2'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger text-center w-50 container mt-2'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <%=link_to "Group Family Transactions", root_path, class: "navbar-brand text-white" %>
  <!-- Collapse button -->
  <button class="navbar-toggler second-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent23"
    aria-controls="navbarSupportedContent23" aria-expanded="false" aria-label="Toggle navigation">
    <div class="animated-icon2"><span></span><span></span><span></span><span></span></div>
  </button>
<%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe %>
  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent23">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
    <!-- Links -->

  </div>
  <!-- Collapsible content -->

  <div class="collapse navbar-collapse container " id="navbarNav">
    <% if logged_in?%>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active mr-4">
        <%= link_to "My transactions", user_path(current_user), class: "nav-link text-white" %>
      </li>
      <li class="nav-item active mr-4">
        <%= link_to "All transactions", root_path, class: "nav-link text-white" %>
      </li> 
      <li class="nav-item active mr-4">
        <%= link_to "All Groups", groups_path, class: "nav-link text-white" %>
      </li> 
      <li class="nav-item mr-4">
      <%=link_to('Logout', logout_path, class: "btn btn-xs btn-danger shadow mr-3", method: :delete)%>
      </li>
    </ul>
    <% else %>

     <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
          <%= link_to "Sign In", login_path, class: "nav-link text-white " %>
        </li>
       <li class="nav-item active">
        <%= link_to "Sign Up", new_user_path, class: "nav-link text-white " %>
      </li>
    </ul>
    
  <% end -%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="page-container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%=render 'layouts/footer' %>  
    </div>
  </body>
</html>

app/views/shared/_error_messages.erb
 <% if @transaction.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(@transaction.errors.count, "error") %>.
</div>
<ul>
<% @transaction.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/transactions/index.html.erb
<div class = "container mt-3"> 
<h3>All Transactions</h3>  
<% @transactions.order("id desc").each do |transaction| %>
  <div class = 'row'> 
      <div class = 'col-10 card p-3 text-center'>       
        <% if logged_in? %>
            <p><strong>Host:</strong> <%= transaction.user.username.capitalize %></p>
        <% end -%>
          <p><strong>Transaction name:</strong> <%= transaction.name %></p>
          <p><strong>Amount:</strong> $<%= transaction.amount %></p>
          <p><strong>created at:</strong> <%= transaction.created_at %></p> 
      </div>
    
   </div>
   <% end %>
</div>
      

app/views/transactions/new.html.erb
<div class="row container h-4">
  <div class="col-6 ">
    <div class="container mt-3 card-bg shdw p-3">
  <h1 class="mt-3">Create a Transaction</h1>
<%= form_with(model: @transaction, class: "shadow p-3 mb-3 form-bg rounded", local: true) do |f| %>
<%= render 'shared/error_messages' %>
<div class="form-group ">
  <%=f.label :name%>
  <%=f.text_field :name, class: "form-control"%>
</div>
<div class="form-group ">
  <%=f.label :amount%>
  <%=f.text_field :amount, class: "form-control"%>
</div>
<div class="form-group ">
  <%=f.label :group%>
  <%= f.collection_select :group_id, Group.all, :id, :name, prompt: true, class: "form-control" %>
   
</div>
  <div class="form-group">
    <%=f.submit "Create Transaction", class: "btn btn-success"%>
  </div>
  
<% end %>
</div>
    
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container text-center card">
   <h1>Name:<%= @transaction.name %></h1>
   <h1>Amount:<%= @transaction.amount %></h1>
   <h1>Name:<%= @transaction.group.name %></h1>
        <h3>Host: <%= @transaction.user.username.capitalize %></h3>
    <hr>
  
    <p><%= link_to 'ADD NEW', new_transaction_path, class: 'btn btn-success' %></p>

    <p><%= link_to 'Home', root_path, class: 'btn btn-warning' %></p>
</div>

app/views/users/new.html.erb
<div class="container mt-3 w-50 card-bg shdw p-3">
	<h1 class="mt-3">Sign up</h1>
<%= form_with model: @user, class: "form-group" do |f| %>
<div class="form-group ">
	<%=f.label :username%>
  <%=f.text_field :username, class: "form-control"%>
</div>
  <div class="form-group">
  	<%=f.submit "Sign Up", class: "btn custom"%>
  </div>
  
<% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
    <%= link_to 'ADD NEW', new_transaction_path, class: 'btn custom mb-2' %>
    <strong>TOTAL: $</strong><%= Transaction.where(:id => [@created_transactions] ).sum(:amount)%>
    <h1>Transactions you created:</h1>
    <% @created_transactions.order("id desc").each do |transaction| %>
    <div class='row'>
        <div class='col-10 card'>
            <p><%= image_tag transaction.group.icon.url class: "icon" %></p>
            <p><strong>Transaction name:</strong>
                <%= transaction.name %>
            </p>
            <p><strong>Amount:</strong>
                $<%= transaction.amount %>
            </p>
            <p><strong>created At:</strong>
                <%= transaction.created_at %>
            </p>
            
        </div>
        
    </div>
    <% end %>
</div>